export const StartDummyDataTalep = [
  {
    id : "HT1000",
    type: "ht",
    typeName :"Hijyen Ürünleri",
    addressDes: "Akshya Nagar 1st Block 1st Cross, Rammurthy",
    city: "Gaziantep",
    details:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Adipisci beatae, consectetur ea earum explicabo incidunt, molestiae natus necessitatibus perferendis perspiciatis quasi quis repellat similique, tempora vel. Consequuntur ducimus nam quam!",
    email: "okanay@gmail.com",
    kvk: "true",
    name: "Okan Ay",
    phone: "532 534 52 18",
    status: 0,
    street: "Nizip",
    time: 1676585386548,
    state : 0
  },
  {
    id : "CT1000",
    type: "ct",
    typeName :"Çadır İhtiyacı",
    addressDes: "Akshya Nagar 1st Block 1st Cross, Rammurthy",
    city: "Adana",
    details:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Adipisci beatae, consectetur ea earum explicabo incidunt, molestiae natus necessitatibus perferendis perspiciatis quasi quis repellat similique, tempora vel. Consequuntur ducimus nam quam!",
    email: "ahmetkaya@gmail.com",
    kvk: "true",
    name: "Ahmet Kaya",
    phone: "544 154 92 21",
    status: 2,
    street: "Ceyhan",
    time: 1676479386548,
    state : 1
  },
  {
    id : "GT1000",
    type: "gt",
    typeName :"Gıda Ürünleri",
    addressDes: "Akshya Nagar 1st Block 1st Cross, Rammurthy",
    city: "Kahramanmaraş",
    details:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Adipisci beatae, consectetur ea earum explicabo incidunt, molestiae natus necessitatibus perferendis perspiciatis quasi quis repellat similique, tempora vel. Consequuntur ducimus nam quam!",
    email: "kemalerdogan@gmail.com",
    kvk: "true",
    name: "Kemal Tayyip Erdogan",
    phone: "535 415 2491",
    status: 1,
    street: "Onikişubat",
    time: 1676481386548,
    state : 2
  },
  {
    id : "IT1000",
    type: "it",
    typeName :"İlaç İhtiyacı",
    addressDes: "Akshya Nagar 1st Block 1st Cross, Rammurthy",
    city: "Kilis",
    details:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Adipisci beatae, consectetur ea earum explicabo incidunt, molestiae natus necessitatibus perferendis perspiciatis quasi quis repellat similique, tempora vel. Consequuntur ducimus nam quam!",
    email: "ahmetkaya@gmail.com",
    kvk: "true",
    name: "Atabey Matuş",
    phone: "535 416 24 11",
    status: 1,
    street: "Polateli",
    time: 1676487386548,
    state : 0
  },
  {
    id : "BT1000",
    type: "bt",
    typeName :"Barınma İhtiyacı",
    addressDes: "Akshya Nagar 1st Block 1st Cross, Rammurthy",
    city: "Adıyaman",
    details:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Adipisci beatae, consectetur ea earum explicabo incidunt, molestiae natus necessitatibus perferendis perspiciatis quasi quis repellat similique, tempora vel. Consequuntur ducimus nam quam!",
    email: "kemalerdogan@gmail.com",
    kvk: "true",
    name: "Okan Ay",
    phone: "535 412 23 91",
    status: 2,
    street: "Samsat",
    time: 1676488386548,
    state : 0
  },

  {
    id : "HT1001",
    type: "ht",
    typeName :"Hijyen Ürünleri",
    addressDes: "Akshya Nagar 1st Block 1st Cross, Rammurthy",

    city: "Gaziantep",
    details:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Adipisci beatae, consectetur ea earum explicabo incidunt, molestiae natus necessitatibus perferendis perspiciatis quasi quis repellat similique, tempora vel. Consequuntur ducimus nam quam!",
    email: "okanay@gmail.com",
    kvk: "true",
    name: "Okan Ay",
    phone: "532 534 52 18",
    status: 0,
    street: "Nizip",
    time: 1676585386548,
    state : 0
  },
  {
    id : "CT1001",
    type: "ct",
    typeName :"Çadır İhtiyacı",
    addressDes: "Akshya Nagar 1st Block 1st Cross, Rammurthy",

    city: "Adana",
    details:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Adipisci beatae, consectetur ea earum explicabo incidunt, molestiae natus necessitatibus perferendis perspiciatis quasi quis repellat similique, tempora vel. Consequuntur ducimus nam quam!",
    email: "ahmetkaya@gmail.com",
    kvk: "true",
    name: "Ahmet Kaya",
    phone: "544 154 92 21",
    status: 2,
    street: "Ceyhan",
    time: 1676479386548,
    state : 1
  },
  {
    id : "GT1001",
    type: "gt",
    typeName :"Gıda Ürünleri",
    addressDes: "Akshya Nagar 1st Block 1st Cross, Rammurthy",
    city: "Kahramanmaraş",
    details:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Adipisci beatae, consectetur ea earum explicabo incidunt, molestiae natus necessitatibus perferendis perspiciatis quasi quis repellat similique, tempora vel. Consequuntur ducimus nam quam!",
    email: "kemalerdogan@gmail.com",
    kvk: "true",
    name: "Kemal Tayyip Erdogan",
    phone: "535 415 2491",
    status: 1,
    street: "Onikişubat",
    time: 1676481386548,
    state : 2
  },
  {
    id : "IT1001",
    type: "it",
    typeName :"İlaç İhtiyacı",
    addressDes: "Akshya Nagar 1st Block 1st Cross, Rammurthy",
    city: "Kilis",
    details:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Adipisci beatae, consectetur ea earum explicabo incidunt, molestiae natus necessitatibus perferendis perspiciatis quasi quis repellat similique, tempora vel. Consequuntur ducimus nam quam!",
    email: "ahmetkaya@gmail.com",
    kvk: "true",
    name: "Atabey Matuş",
    phone: "535 416 24 11",
    status: 1,
    street: "Polateli",
    time: 1676487386548,
    state : 0
  },
  {
    id : "BT1001",
    type: "bt",
    typeName :"Barınma İhtiyacı",
    addressDes: "Akshya Nagar 1st Block 1st Cross, Rammurthy",

    city: "Adıyaman",
    details:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Adipisci beatae, consectetur ea earum explicabo incidunt, molestiae natus necessitatibus perferendis perspiciatis quasi quis repellat similique, tempora vel. Consequuntur ducimus nam quam!",
    email: "kemalerdogan@gmail.com",
    kvk: "true",
    name: "Mert Aşçı",
    phone: "535 412 23 91",
    status: 2,
    street: "Samsat",
    time: 1676488386548,
    state : 1
  },

];
export const StartDummyDataDestek = [
  {
    id : "KD1000",
    type: "kd",
    typeName :"Konaklama Destek",
    name: "Okan Ay",
    email: "okanay@gmail.com",
    phone: "532 534 52 18",
    state : 0,
    status: 0,
    details:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Adipisci beatae, consectetur ea earum explicabo incidunt, molestiae natus necessitatibus perferendis perspiciatis quasi quis repellat similique, tempora vel. Consequuntur ducimus nam quam!",
    time: 1676585386548,
    kvk: "true",
    info1: "4 Kişi",
    info2: "Süresiz",
    info3: "",
  },
  {
    id : "AKD1000",
    type: "akd",
    typeName :"Arama Kurtarma",
    name: "Osman Asci",
    email: "okanay@gmail.com",
    phone: "532 534 52 18",
    state : 1,
    status: 0,
    details:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Adipisci beatae, consectetur ea earum explicabo incidunt, molestiae natus necessitatibus perferendis perspiciatis quasi quis repellat similique, tempora vel. Consequuntur ducimus nam quam!",
    time: 1676995386548,
    kvk: "true",
    info1: "Deneyimsiz",
    info2: "Sertifikasız",
    info3: "",
  },
  {
    id : "CD1000",
    type: "cd",
    typeName :"Çevirmenlik Destek",
    name: "Mert Ay",
    email: "okanay@gmail.com",
    phone: "532 534 52 18",
    state : 0,
    status: 0,
    details:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Adipisci beatae, consectetur ea earum explicabo incidunt, molestiae natus necessitatibus perferendis perspiciatis quasi quis repellat similique, tempora vel. Consequuntur ducimus nam quam!",
    time: 1676785386548,
    kvk: "true",
    info1: "İngilizce",
    info2: "Fransızca",
    info3: "Almanca",
  },
  {
    id : "OBD1000",
    type: "obd",
    typeName :"Operasyonlarda Bulunabilirim",
    name: "Atabey Matus",
    email: "okanay@gmail.com",
    phone: "532 534 52 18",
    state : 1,
    status: 0,
    details:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Adipisci beatae, consectetur ea earum explicabo incidunt, molestiae natus necessitatibus perferendis perspiciatis quasi quis repellat similique, tempora vel. Consequuntur ducimus nam quam!",
    time: 1676785386548,
    kvk: "true",
    info1: "Çadır Kurabilirim",
    info2: "Profesyönel",
    info3: "",
  },
  {
    id : "NTD1000",
    type: "ntd",
    typeName :"Nakliye ve Taşıma",
    name: "Atabey Matus",
    email: "okanay@gmail.com",
    phone: "532 534 52 18",
    state : 2,
    status: 0,
    details:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Adipisci beatae, consectetur ea earum explicabo incidunt, molestiae natus necessitatibus perferendis perspiciatis quasi quis repellat similique, tempora vel. Consequuntur ducimus nam quam!",
    time: 1676785386548,
    kvk: "true",
    info1: "Depremzede İnsan",
    info2: "Edirne",
    info3: "Lüleburgaz",
  },

  {
    id : "KD1001",
    type: "kd",
    typeName :"Konaklama Destek",
    name: "Okan Ay",
    email: "okanay@gmail.com",
    phone: "532 534 52 18",
    state : 0,
    status: 0,
    details:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Adipisci beatae, consectetur ea earum explicabo incidunt, molestiae natus necessitatibus perferendis perspiciatis quasi quis repellat similique, tempora vel. Consequuntur ducimus nam quam!",
    time: 1676585386548,
    kvk: "true",
    info1: "4 Kişi",
    info2: "Süresiz",
    info3: "",
  },
  {
    id : "AKD1001",
    type: "akd",
    typeName :"Arama Kurtarma",
    name: "Osman Asci",
    email: "okanay@gmail.com",
    phone: "532 534 52 18",
    state : 1,
    status: 0,
    details:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Adipisci beatae, consectetur ea earum explicabo incidunt, molestiae natus necessitatibus perferendis perspiciatis quasi quis repellat similique, tempora vel. Consequuntur ducimus nam quam!",
    time: 1676995386548,
    kvk: "true",
    info1: "Deneyimsiz",
    info2: "Sertifikasız",
    info3: "",
  },
  {
    id : "CD1001",
    type: "cd",
    typeName :"Çevirmenlik Destek",
    name: "Mert Ay",
    email: "okanay@gmail.com",
    phone: "532 534 52 18",
    state : 0,
    status: 0,
    details:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Adipisci beatae, consectetur ea earum explicabo incidunt, molestiae natus necessitatibus perferendis perspiciatis quasi quis repellat similique, tempora vel. Consequuntur ducimus nam quam!",
    time: 1676785386548,
    kvk: "true",
    info1: "İngilizce",
    info2: "Fransızca",
    info3: "Almanca",
  },
  {
    id : "OBD1001",
    type: "obd",
    typeName :"Operasyonlarda Bulunabilirim",
    name: "Atabey Matus",
    email: "okanay@gmail.com",
    phone: "532 534 52 18",
    state : 1,
    status: 0,
    details:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Adipisci beatae, consectetur ea earum explicabo incidunt, molestiae natus necessitatibus perferendis perspiciatis quasi quis repellat similique, tempora vel. Consequuntur ducimus nam quam!",
    time: 1676785386548,
    kvk: "true",
    info1: "Çadır Kurabilirim",
    info2: "Profesyönel",
    info3: "",
  },
  {
    id : "NTD1001",
    type: "ntd",
    typeName :"Nakliye ve Taşıma",
    name: "Atabey Matus",
    email: "okanay@gmail.com",
    phone: "532 534 52 18",
    state : 2,
    status: 0,
    details:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Adipisci beatae, consectetur ea earum explicabo incidunt, molestiae natus necessitatibus perferendis perspiciatis quasi quis repellat similique, tempora vel. Consequuntur ducimus nam quam!",
    time: 1676785386548,
    kvk: "true",
    info1: "Depremzede İnsan",
    info2: "Edirne",
    info3: "Lüleburgaz",
  },
];
