export const imageData = [
  {
    key: "imageDataBT",
    name: "bt",
    url: "/form/bt",
    src: "/svg/cabin.svg",
    alt: "Barınmaya İhtiyacım Var",
    description: "Barınmaya İhtiyacım Var",
  },
  {
    key: "imageDataCT",
    name: 'ct',
    url: "/form/ct",
    src: "/svg/camp.svg",
    alt: "Çadıra İhtiyacım Var",
    description: "Çadıra İhtiyacım Var",
  },
  {
    key: "imageDataGT",
    name: "gt",
    url: "/form/gt",
    src: "/svg/foods.svg",
    alt: "Gıdaya İhtiyacım Var",
    description: "Gıdaya İhtiyacım Var",
  },
  {
    key: "imageDataIT",
    name: "it",
    url: "/form/it",
    src: "/svg/medicine.svg",
    alt: "İlaca İhtiyacım Var",
    description: "İlaca İhtiyacım Var",
  },
  {
    key: "imageDataHT",
    name: "ht",
    url: "/form/ht",
    src: "/svg/amenities.svg",
    alt: "Hijyen Ürünlerine İhtiyacım Var",
    description: "Hijyen Ürünlerine İhtiyacım Var",
  },
  {
    key: "imageDataKD",
    name: "kd",
    url: "/form/kd",
    src: "/svg/house.svg",
    alt: "Konaklama",
    description: "Konaklama",
  },
  {
    key: "imageDataAKD",
    name: "akd",
    url: "/form/akd",
    src: "/svg/footprints.svg",
    alt: "Arama",
    description: "Arama",
  },
  {
    key: "imageDataOBD",
    name: "obd",
    url: "/form/obd",
    src: "/svg/constructionWorker.svg",
    alt: "Operasyonlarda Bulunabilirim",
    description: "Operasyon",
  },
  {
    key: "imageDataNTD",
    name: "ntd",
    url: "/form/ntd",
    src: "/svg/busDriver.svg",
    alt: "Nakliye",
    description: "Nakliye",
  },
  {
    key: "imageDataCD",
    name: "cd",
    url: "/form/cd",
    src: "/svg/translator.svg",
    alt: "Cevirmenlik",
    description: "Cevirmenlik",
  },
];

